'use strict';
const G = require('./generate.js');
const { dtable, tblCap, figCap, chHead, sh, p, cp, lp, bl, bls, tr, tc, trow, tbl, pt, AlignmentType } = G;

// ── CHAPTER 5: IMPLEMENTATION ────────────────────────────
function chapter5() {
  return [
    chHead('CHAPTER 5: IMPLEMENTATION'),
    sh('5.1 Development Environment and Tools'),
    p('The project was developed on a Windows 10 machine using Visual Studio Code as the primary IDE. Node.js v18 and npm v9 were used for backend development. MongoDB Atlas (cloud) was used as the database during development. The backend and frontend were run concurrently using separate terminal sessions with nodemon and react-scripts respectively.', { firstLine: true }),
    bl(),
    p('Git was used for version control and the project was pushed to GitHub for backup and collaboration. Postman was used extensively for API testing during development.', { firstLine: true }),

    sh('5.2 Project Structure'),
    p('The project follows a monorepo structure with clear separation between the server and client:', { firstLine: true }),
    bl(),
    tbl([
      trow([tc('sixthsem_project/', { fill: '1F3864', bold: true, tc: 'FFFFFF' })]),
      trow([tc('├── server/                     ← Node.js + Express.js Backend', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│   ├── index.js                ← Express app entry point (PORT 5000)', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│   ├── config/database.js       ← MongoDB connection via Mongoose', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│   ├── middleware/auth.js        ← JWT authenticateToken + requireAdmin', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│   ├── models/                  ← Mongoose schemas', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│   │   ├── User.js, Product.js, Supplier.js, Category.js', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│   │   ├── PurchaseOrder.js, SalesOrder.js, SalesHistory.js', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│   └── routes/                  ← Express route handlers', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│       ├── auth.js, users.js, products.js, suppliers.js', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│       ├── categories.js, purchaseOrders.js, salesOrders.js', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│       ├── reports.js, algorithms.js', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('├── client/                      ← React.js Frontend (PORT 3000)', { fill: 'E2EFDA', bold: true, align: AlignmentType.LEFT })]),
      trow([tc('│   └── src/', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│       ├── App.js               ← Root component with all routes', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│       ├── context/AuthContext.js← Global auth state (JWT, user info)', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│       └── components/', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│           ├── Auth/             ← Login, Register, ChangePassword', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│           ├── Dashboard/        ← Overview stats and charts', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│           ├── Products/         ← Product list, CRUD forms, barcode', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│           ├── Suppliers/        ← Supplier management', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│           ├── PurchaseOrders/   ← PO management', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│           ├── SalesOrders/      ← Sales order management', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│           ├── Reports/          ← Charts and analytics', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│           ├── Algorithms/       ← Algorithm runner UI', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('│           ├── Users/            ← User management (Admin only)', { fill: 'FFFFFF', align: AlignmentType.LEFT })]),
      trow([tc('│           └── Layout/Navbar.js  ← Navigation sidebar', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
      trow([tc('├── .env                          ← JWT_SECRET, MONGODB_URI, PORT', { fill: 'FCE4D6', align: AlignmentType.LEFT })]),
      trow([tc('└── package.json                  ← Root dependencies (backend)', { fill: 'F8F8F8', align: AlignmentType.LEFT })]),
    ]),
    figCap('Project Folder Structure'),

    sh('5.3 Module Implementation Details'),
    p('5.3.1 Authentication Module', { bold: true }),
    p('The authentication module implements secure login, registration, and session management. Registration uses express-validator for input validation. Passwords are hashed using bcryptjs with 10 salt rounds before storage. Login generates a JWT token valid for 24 hours, signed with a secret key from environment variables. The token contains the user\'s id, username, email, and role. All protected routes verify this token via the authenticateToken middleware.', { firstLine: true }),
    bl(),
    p('A notable security feature is the account approval workflow: newly registered accounts are set to "pending" status and cannot login until an admin explicitly activates them to "active" status. This prevents unauthorized access.', { firstLine: true }),
    bl(),
    p('5.3.2 Product Management Module', { bold: true }),
    bl(),
    tblCap('API Endpoints – Product Module'),
    dtable(['Method', 'Endpoint', 'Access', 'Description'], [
      ['GET', '/api/products', 'All Users', 'List all products with optional search, category, supplier, stock filters'],
      ['GET', '/api/products/:id', 'All Users', 'Get a single product by MongoDB ObjectId'],
      ['GET', '/api/products/barcode/:barcode', 'All Users', 'Lookup product by barcode value'],
      ['POST', '/api/products', 'Admin Only', 'Create new product (validates SKU uniqueness)'],
      ['PUT', '/api/products/:id', 'Admin Only', 'Update product details (does not change SKU)'],
      ['DELETE', '/api/products/:id', 'Admin Only', 'Permanently delete a product'],
    ], [10, 35, 15, 40]),
    bl(),
    p('5.3.3 Purchase Order Module', { bold: true }),
    bl(),
    tblCap('API Endpoints – Purchase Order Module'),
    dtable(['Method', 'Endpoint', 'Access', 'Description'], [
      ['GET', '/api/purchase-orders', 'All Users', 'List all purchase orders'],
      ['GET', '/api/purchase-orders/:id', 'All Users', 'Get a purchase order with items'],
      ['POST', '/api/purchase-orders', 'All Users', 'Create purchase order (staff/admin). Default status pending'],
      ['PUT', '/api/purchase-orders/:id/status', 'Admin Only', 'Update status; when received, stock is incremented and InventoryTransaction records are created'],
    ], [10, 45, 15, 30]),
    bl(),
    p('5.3.4 Sales Order Module', { bold: true }),
    bl(),
    tblCap('API Endpoints – Sales Order Module'),
    dtable(['Method', 'Endpoint', 'Access', 'Description'], [
      ['GET', '/api/sales-orders', 'All Users', 'List all sales orders'],
      ['GET', '/api/sales-orders/:id', 'All Users', 'Get a sales order with items'],
      ['POST', '/api/sales-orders', 'All Users', 'Create sales order (validates stock, decrements stock, writes SalesHistory)'],
      ['PUT', '/api/sales-orders/:id/status', 'Admin Only', 'Update lifecycle status'],
    ], [10, 45, 15, 30]),
    bl(),
    p('5.3.5 Reports Module', { bold: true }),
    p('5.3.3 Reports Module', { bold: true }),
    bl(),
    dtable(['Endpoint', 'Description', 'Key Fields Returned'], [
      ['GET /api/reports/stock-levels', 'All products sorted by quantity (low to high)', 'sku, name, quantity, reorder_level, status'],
      ['GET /api/reports/sales-trends', 'Daily aggregated sales for last N days (default 30)', 'date, total_quantity, total_revenue, products_sold'],
      ['GET /api/reports/inventory-turnover', 'Turnover ratio per product', 'sku, name, quantity, total_sold, turnover_rate'],
      ['GET /api/reports/low-stock-alerts', 'Products where quantity ≤ reorder_level', 'sku, name, quantity, reorder_level, supplier_name'],
      ['GET /api/reports/top-selling', 'Top N products by units sold in last N days', 'sku, name, total_sold, total_revenue'],
    ], [30, 35, 35]),
    bl(),
    p('5.3.6 Authentication Middleware Implementation', { bold: true }),
    p('Two middleware functions are defined in server/middleware/auth.js:', { firstLine: true }),
    bl(),
    tbl([
      trow([
        tc('authenticateToken', { fill: '1F3864', bold: true, tc: 'FFFFFF', w: 30 }),
        tc('Extracts Bearer token from Authorization header. Verifies JWT against JWT_SECRET. On success, attaches decoded user payload to req.user and calls next(). Returns 401 if no token, 403 if invalid/expired.', { align: AlignmentType.LEFT, w: 70 }),
      ]),
      trow([
        tc('requireAdmin', { fill: 'DAE3F3', bold: true, w: 30 }),
        tc('Called after authenticateToken. Checks req.user.role === "admin". Returns 403 Forbidden if the user is a staff member. Used on all product, supplier, category, purchase order, and user management routes.', { align: AlignmentType.LEFT, w: 70 }),
      ]),
    ]),

    sh('5.4 How to Run the Project'),
    p('Step 1: Clone the repository and install all dependencies:', { bold: true }),
    tbl([trow([tc('npm run install-all', { fill: '1E1E1E', tc: 'D4D4D4', align: AlignmentType.LEFT })])]),
    bl(),
    p('Step 2: Configure environment variables in .env file:', { bold: true }),
    tbl([trow([tc('PORT=5000\nMONGODB_URI=mongodb://localhost:27017/inventory_db\nJWT_SECRET=your_super_secret_key_here\nNODE_ENV=development', { fill: '1E1E1E', tc: 'D4D4D4', align: AlignmentType.LEFT })])]),
    bl(),
    p('Step 3: Start the backend server:', { bold: true }),
    tbl([trow([tc('npm run dev', { fill: '1E1E1E', tc: 'D4D4D4', align: AlignmentType.LEFT })])]),
    bl(),
    p('Step 4: Start the React frontend (in a new terminal):', { bold: true }),
    tbl([trow([tc('npm run client', { fill: '1E1E1E', tc: 'D4D4D4', align: AlignmentType.LEFT })])]),
    bl(),
    p('The backend runs at http://localhost:5000 and the React frontend at http://localhost:3000. The React app is configured to proxy all /api requests to the backend automatically.', { firstLine: true }),
  ];
}

// ── CHAPTER 6: TESTING ────────────────────────────────────
function chapter6() {
  return [
    chHead('CHAPTER 6: TESTING'),
    sh('6.1 Testing Strategy'),
    p('The system was tested using a combination of: (1) Manual functional testing through the browser UI, (2) API testing using Postman for all REST endpoints, and (3) Boundary and edge-case testing for algorithm modules. Test cases were designed to cover both positive (expected behavior) and negative (error handling) scenarios.', { firstLine: true }),

    sh('6.2 Test Cases and Results'),
    bl(),
    tblCap('Test Cases and Results'),
    dtable(
      ['TC#', 'Module', 'Test Description', 'Expected Result', 'Actual Result', 'Status'],
      [
        ['TC-01', 'Auth', 'Login with correct username and password', 'JWT token returned, redirect dashboard', 'JWT returned, redirected', '✔ PASS'],
        ['TC-02', 'Auth', 'Login with wrong password', '401 Invalid credentials error', '401 returned', '✔ PASS'],
        ['TC-03', 'Auth', 'Register new user with valid input', 'Account created with pending status', 'Account created, pending', '✔ PASS'],
        ['TC-04', 'Auth', 'Register with duplicate username', '400 User already exists error', '400 returned', '✔ PASS'],
        ['TC-05', 'Auth', 'Login with pending account', '403 Account pending approval', '403 returned', '✔ PASS'],
        ['TC-06', 'Auth', 'Login with disabled account', '403 Account is disabled', '403 returned', '✔ PASS'],
        ['TC-07', 'Auth', 'Access protected route without JWT', '401 Access token required', '401 returned', '✔ PASS'],
        ['TC-08', 'Products', 'Create product as Admin', 'Product saved, 201 returned', 'Product saved', '✔ PASS'],
        ['TC-09', 'Products', 'Create product as Staff (unauthorized)', '403 Admin access required', '403 returned', '✔ PASS'],
        ['TC-10', 'Products', 'Create product with duplicate SKU', '400 SKU already exists', '400 returned', '✔ PASS'],
        ['TC-11', 'Products', 'Search products by keyword', 'Matching products returned', 'Correct results', '✔ PASS'],
        ['TC-12', 'Products', 'Lookup product by barcode', 'Correct product returned', 'Product found', '✔ PASS'],
        ['TC-13', 'Products', 'Delete product as Admin', '200 Product deleted successfully', 'Deleted correctly', '✔ PASS'],
        ['TC-14', 'Suppliers', 'Add new supplier', 'Supplier created in DB', 'Created correctly', '✔ PASS'],
        ['TC-15', 'Auto-Reorder', 'Run with products below reorder level', 'POs auto-created per supplier', 'POs created', '✔ PASS'],
        ['TC-16', 'Auto-Reorder', 'Product with no supplier assigned', 'Product skipped with reason message', 'Skipped with reason', '✔ PASS'],
        ['TC-17', 'Auto-Reorder', 'Run when all stock is sufficient', '"No products need reordering" returned', 'Correct message', '✔ PASS'],
        ['TC-18', 'Demand Forecast', 'Forecast with no sales history', 'Returns insufficient_data, all zeros', 'Correct response', '✔ PASS'],
        ['TC-19', 'Demand Forecast', 'Forecast with existing sales history', 'Returns 30/60/90 day forecasts', 'Forecasts returned', '✔ PASS'],
        ['TC-20', 'Optimization', 'Run with mix of fast/slow products', 'Correct demand classification returned', 'Classifications correct', '✔ PASS'],
        ['TC-21', 'Reports', 'Low stock alerts report', 'Only items with qty ≤ reorder_level', 'Correct items returned', '✔ PASS'],
        ['TC-22', 'Reports', 'Top selling products report', 'Sorted by total sold descending', 'Correct sort order', '✔ PASS'],
        ['TC-23', 'Users', 'Admin approves pending user', 'Status changes to active, can login', 'Status updated', '✔ PASS'],
        ['TC-24', 'Users', 'Admin disables active user', 'Status changes to disabled, cannot login', 'Status updated', '✔ PASS'],
        ['TC-25', 'PurchaseOrders', 'Create PO manually as Admin', 'PO created with pending status', 'PO created', '✔ PASS'],
      ],
      [5, 12, 25, 23, 20, 10]
    ),
    bl(),
    p('All 25 test cases passed successfully, demonstrating that the system functions correctly across all core modules under both normal and edge-case conditions.', { firstLine: true }),
  ];
}

// ── CHAPTER 7: CONCLUSION ────────────────────────────────
function chapter7() {
  return [
    chHead('CHAPTER 7: CONCLUSION AND FUTURE WORK'),
    sh('7.1 Conclusion'),
    p('This project successfully designed and developed a comprehensive, web-based Inventory Management System (IMS) using the MERN stack. The system addresses the real-world inventory management challenges faced by small and medium businesses in Nepal by providing a centralized, secure, and feature-rich platform.', { firstLine: true }),
    bl(),
    p('The key achievements of this project include:', { firstLine: true }),
    bl(),
    lp('•   A fully functional role-based web application with Admin and Staff access levels.'),
    lp('•   JWT-secured authentication with admin-controlled account approval workflow.'),
    lp('•   Complete CRUD management for products, categories, suppliers, purchase orders, and sales orders.'),
    lp('•   Three intelligent algorithmic modules — Automated Reordering, Demand Forecasting (SMA), and Inventory Optimization.'),
    lp('•   Five report types rendered as interactive charts using Recharts.'),
    lp('•   Barcode scanning integration using HTML5-QRCode.'),
    lp('•   A RESTful backend with nine route modules, all secured with JWT middleware.'),
    lp('•   100% pass rate across 25 documented test cases.'),
    bl(),
    p('This project provided practical experience in full-stack JavaScript development, RESTful API design, NoSQL database modeling with Mongoose, React component architecture, Context API for state management, and the application of algorithmic thinking to solve real business problems.', { firstLine: true }),

    sh('7.2 Limitations'),
    lp('1.   No email or SMS notification system — stock alerts and account approvals require manual checking.'),
    lp('2.   Basic demand forecasting — the Simple Moving Average method, while effective, is less accurate than advanced methods like ARIMA or exponential smoothing.'),
    lp('3.   No multi-warehouse support — the system assumes a single store or warehouse location.'),
    lp('4.   No audit trail — the system does not record a history of who changed what and when.'),
    lp('5.   No PDF/Excel report export — reports are only viewable within the browser.'),
    lp('6.   No real-time updates — multiple simultaneous users may face stale data without page refresh.'),

    sh('7.3 Future Enhancements'),
    lp('1.   Email Notifications: Integrate Nodemailer to send automatic low-stock alerts and account approval emails.'),
    lp('2.   Advanced Forecasting: Implement ARIMA or Prophet-based machine learning forecasting for higher accuracy.'),
    lp('3.   Mobile App: Develop a React Native companion app for mobile barcode scanning and inventory management.'),
    lp('4.   Multi-branch Support: Extend the system to manage inventory across multiple physical locations.'),
    lp('5.   Audit Log: Track all create, update, delete actions with user ID, timestamp, and before/after values.'),
    lp('6.   PDF/Excel Export: Allow all reports to be downloaded in PDF or Excel format using pdfmake or exceljs.'),
    lp('7.   Real-time Updates: Integrate Socket.io for live inventory updates across concurrent user sessions.'),
    lp('8.   GraphQL API: Migrate the REST API to GraphQL for more efficient, flexible data fetching from the frontend.'),
  ];
}

// ── REFERENCES ────────────────────────────────────────────
function references() {
  return [
    chHead('REFERENCES'),
    bl(),
    lp('1.  MongoDB, Inc. (2024). MongoDB Documentation. Retrieved from https://www.mongodb.com/docs/'),
    bl(),
    lp('2.  OpenJS Foundation. (2024). Express.js – Fast, unopinionated, minimalist web framework for Node.js. Retrieved from https://expressjs.com/'),
    bl(),
    lp('3.  Meta Open Source. (2024). React – A JavaScript library for building user interfaces. Retrieved from https://react.dev/'),
    bl(),
    lp('4.  OpenJS Foundation. (2024). Node.js Documentation. Retrieved from https://nodejs.org/'),
    bl(),
    lp('5.  Mongoose. (2024). Mongoose – Elegant MongoDB object modeling for Node.js. Retrieved from https://mongoosejs.com/'),
    bl(),
    lp('6.  Auth0. (2024). Introduction to JSON Web Tokens. Retrieved from https://jwt.io/introduction'),
    bl(),
    lp('7.  Kellect Inc. (2024). Recharts – A composable charting library built on React. Retrieved from https://recharts.org/'),
    bl(),
    lp('8.  Minhazul. (2024). HTML5-QRCode – Quickly scan QR codes and barcodes. Retrieved from https://github.com/mebjas/html5-qrcode'),
    bl(),
    lp('9.  Pressman, R. S. (2014). Software Engineering: A Practitioner\'s Approach (8th ed.). McGraw-Hill Education.'),
    bl(),
    lp('10. Heizer, J., & Render, B. (2014). Operations Management: Sustainability and Supply Chain Management (11th ed.). Pearson Education.'),
    bl(),
    lp('11. Duckett, J. (2014). JavaScript and JQuery: Interactive Front-End Web Development. John Wiley & Sons.'),
    bl(),
    lp('12. Osmani, A. (2012). Learning JavaScript Design Patterns. O\'Reilly Media.'),
    bl(),
    lp('13. Tribhuvan University, Institute of Science and Technology. (2024). BCA Project Guidelines. Kathmandu: IOST Publication.'),
  ];
}

module.exports = { chapter5, chapter6, chapter7, references };
